### PR TITLE
ARM compilation support

### PR DESCRIPTION
**Pull request by sr229**
Travis recently added ARM compile support so we'll use that instead of hacking our way to ARM support.

This will supersede #23

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
How do you plan to properly test it on dev machines?

**Comment by sr229** [comment]
> Removing the arm Dockerfiles makes it really hard to properly test arm64 on my amd64 machine without having a arm64 board by hand or an emu ready.

There's already a way to test ARM images using the QEMU user static Docker images, making my previous strategy obsolete. 

The point is to consolidate everything into a single codebase, so every environment gets the same result. The old approach is really dirty and I actually hate that version.

I have a Raspberry Pi 4 and I've been testing code-server personally so I'm just configuring the CIs to build Docker images for it. 

> This makes it so easy to be lazy and skip testing which leads to poor quality for arm users.

Again we use the same codebase for everything. Where's the *lazy* in that? You all get the same result as with x86 users.

> How do you plan to properly test it on dev machines?

See comment above.

**Comment by SuperSandro2000** [comment]
> There's already a way to test ARM images using the QEMU user static Docker images, making my previous strategy obsolete.

I know this. really handy.

> You all get the same result as with x86 users.

If you think this is true.

**Comment by rogelio-o** [comment]
Any update on this?

**Comment by sr229** [comment]
Superseded by #35

**Pull request closed without merging**
